version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    env_file:
      - ./zookeeper.env
      
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    env_file: 
      - ./broker.env

  mysql-db:
    image: mysql
    container_name: mysql
    hostname: mysql
    env_file:
      - ./db/db.env
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d

  producer:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - kafka-broker

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - mysql-db
      - kafka-broker
    volumes:
      - temperature-db:/var/lib/mysql

volumes:
  temperature-db:

