CREATE DATABASE IF NOT EXISTS kafka;
USE kafka;

CREATE TABLE IF NOT EXISTS temperature(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature FLOAT NOT NULL
)